Update en.lua of qb-towjob
qbcore-framework/qb-towjob pull request #34
Opened 2022-06-03 22:09 UTC by 12LetterMeme

updating some of the grammar used in towjob

2022-06-09 09:08 UTC, MatthewRorke commented
Can you please fix the capitalisations

2022-06-09 15:56 UTC, MatthewRorke requested changes
Hey, sorry I was not specific enough. That's my bad.
I suggested the changes to fix the capitalisations (we shouldn't be capitalising every single word). 

You should be able to just accept the changes from my review and then we can proceed with merging. Thanks for contributing.

2022-06-09 15:56 UTC, MatthewRorke commented on locales/en.lua
>          vehicle_not_correct = "This Is Not The Right Vehicle",
```suggestion
        vehicle_not_correct = "This is not the right Vehicle",
```

2022-06-09 15:56 UTC, MatthewRorke commented on locales/en.lua
> +        failed = "You Have Failed",
```suggestion
        failed = "You have failed",
```

2022-06-09 15:56 UTC, MatthewRorke commented on locales/en.lua
> +        too_far_away = "You Are Too Far Away",
```suggestion
        too_far_away = "You are too far away",
```

2022-06-09 15:56 UTC, MatthewRorke commented on locales/en.lua
> +        no_work_done = "You Have Not Done Any Work Yet",
```suggestion
        no_work_done = "You have not done any work yet",
```

2022-06-09 17:18 UTC, 12LetterMeme commented on locales/en.lua
>          no_deposit = "$%{value} Deposit Required",
I was thinking the same thing initially, but just decided to go with what was originally there which was everything was capitalized.. thought there was a reason for it lmao

2022-06-09 17:19 UTC, 12LetterMeme commented
sorry I made this painful haha

2022-06-10 08:54 UTC, MatthewRorke commented
Not painful at all. People get used to writing in PascalCase and end up writing that way in English, lmao.

Please can you just update your branch to the latest version as we did some merges yesterday and then I will get yours merged in.

2022-06-21 19:29 UTC, merged