Security fix. Fixes #37
qbcore-framework/qb-towjob pull request #38
Opened 2022-07-03 20:35 UTC by tom-osborne

**Describe Pull request**
This PR prevents the player from being kicked when towing a vehicle while still maintaining the distance check. This area of the code could definitely benefit from a full re-work, but this serves to at least make the job useable for now.

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

2022-07-03 21:44 UTC, BerkieBb requested changes

2022-07-03 21:44 UTC, BerkieBb commented on client/main.lua
> +local PlayerJob = QBCore.Functions.GetPlayerData().job
You should make this PlayerData instead of trying to grab the job of a possible nil value which could end the execution of the resource once it errors out, then change PlayerJob to PlayerData.job

2022-07-03 21:44 UTC, BerkieBb commented on server/main.lua
> +        print("KICKED")
A print?

2022-07-03 22:06 UTC, tom-osborne commented on server/main.lua
> +        print("KICKED")
Ah leftover from testing

2022-07-03 22:11 UTC, tom-osborne commented on client/main.lua
> +local PlayerJob = QBCore.Functions.GetPlayerData().job
Done.

2022-07-03 22:11 UTC, tom-osborne commented on server/main.lua
> +        print("KICKED")
Uncommented drop player line and removed comment

2022-07-04 14:05 UTC, BerkieBb approved these changes

2022-07-04 14:26 UTC, merged